import { supabase } from './supabase-config.js';
import { money,numberBR,digits,normalizeBrand,toast } from './utils.js';

const $=s=>document.querySelector(s);let vehicles=[],leads=[],sales=[],photos=[];let selectedFiles=[];let editingId=null;const today=()=>new Date().toISOString().slice(0,10);

async function boot(){const {data:{session}}=await supabase.auth.getSession();session?showApp():showLogin();supabase.auth.onAuthStateChange((_e,s)=>s?showApp():showLogin());}
function showLogin(){$('#loginScreen').classList.remove('hidden');$('#app').classList.add('hidden');}
async function showApp(){$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');await loadAll();goPage('dashboard',document.querySelector('[data-page="dashboard"]'));}
window.login=async e=>{e.preventDefault();const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;const {error}=await supabase.auth.signInWithPassword({email,password});if(error)toast('E-mail ou senha inválidos.','error');};
window.logout=async()=>{await supabase.auth.signOut();};

async function loadAll(){const [v,l,s,p]=await Promise.all([supabase.from('vehicles').select('*').order('created_at',{ascending:false}),supabase.from('leads').select('*').order('contact_date',{ascending:false}),supabase.from('sales').select('*').order('sale_date',{ascending:false}),supabase.from('vehicle_photos').select('*').order('position')]);if(v.error||l.error||s.error||p.error){console.error(v.error,l.error,s.error,p.error);toast('Erro ao carregar dados.','error');return;}vehicles=v.data||[];leads=l.data||[];sales=s.data||[];photos=p.data||[];}

window.goPage=(page,btn)=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');$('#topTitle').textContent={dashboard:'Dashboard',vehicles:'Veículos',leads:'CRM / Leads',sales:'Vendas'}[page];renderPage(page);};
function renderPage(page){if(page==='dashboard')renderDashboard();if(page==='vehicles')renderVehicles();if(page==='leads')renderLeads();if(page==='sales')renderSales();}
function renderDashboard(){const revenue=sales.reduce((a,s)=>a+Number(s.sale_value),0);$('#pageContent').innerHTML=`<div class="page-head"><div><h1>Visão geral</h1><p>Dados em tempo real do Supabase.</p></div></div><div class="stats"><div class="stat"><span>Veículos vendidos</span><strong>${sales.length}</strong></div><div class="stat"><span>Faturamento</span><strong>${money(revenue)}</strong></div><div class="stat"><span>Ticket médio</span><strong>${money(sales.length?revenue/sales.length:0)}</strong></div><div class="stat"><span>Estoque disponível</span><strong>${vehicles.filter(v=>v.status==='Disponível').length}</strong></div></div><div class="panel"><h3>Funil comercial</h3><div class="pipeline">${['Novo','Em atendimento','Proposta enviada','Negociação','Vendido'].map(st=>`<div class="pipe"><strong>${leads.filter(l=>l.status===st).length}</strong><span>${st}</span></div>`).join('')}</div></div>`;}
function renderVehicles(){ $('#pageContent').innerHTML=`<div class="page-head"><div><h1>Veículos</h1><p>Cadastre e edite o estoque no Supabase.</p></div><button class="primary" onclick="openVehicle()">+ Novo veículo</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Veículo</th><th>Ano</th><th>KM</th><th>Preço</th><th>Status</th><th>Ações</th></tr></thead><tbody>${vehicles.map(v=>`<tr><td><b>${normalizeBrand(v.brand)} ${v.model}</b><br><small>${v.version}</small></td><td>${v.year_model}</td><td>${numberBR(v.mileage)}</td><td>${money(v.price)}</td><td><span class="badge">${v.status}</span></td><td><button class="mini" onclick="openVehicle('${v.id}')">Editar</button> <button class="mini danger" onclick="deleteVehicle('${v.id}')">Excluir</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhum veículo cadastrado.</td></tr>'}</tbody></table></div>`;}
function renderLeads(){ $('#pageContent').innerHTML=`<div class="page-head"><div><h1>CRM / Leads</h1><p>Gerencie oportunidades comerciais.</p></div><button class="primary" onclick="openLead()">+ Novo lead</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>Telefone</th><th>Vendedor</th><th>Status</th><th>Data</th><th>Ações</th></tr></thead><tbody>${leads.map(l=>`<tr><td><b>${l.name}</b><br><small>${l.email||''}</small></td><td>${l.phone}</td><td>${l.seller||'-'}</td><td>${l.status}</td><td>${new Date(l.contact_date+'T12:00').toLocaleDateString('pt-BR')}</td><td><button class="mini danger" onclick="deleteLead('${l.id}')">Excluir</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhum lead.</td></tr>'}</tbody></table></div>`;}
function renderSales(){const total=sales.reduce((a,s)=>a+Number(s.sale_value),0);$('#pageContent').innerHTML=`<div class="page-head"><div><h1>Vendas</h1><p>Resultados registrados no banco.</p></div><button class="primary" onclick="openSale()">+ Registrar venda</button></div><div class="stats"><div class="stat"><span>Vendidos</span><strong>${sales.length}</strong></div><div class="stat"><span>Faturamento</span><strong>${money(total)}</strong></div><div class="stat"><span>Ticket médio</span><strong>${money(sales.length?total/sales.length:0)}</strong></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Cliente</th><th>Vendedor</th><th>Pagamento</th><th>Valor</th></tr></thead><tbody>${sales.map(s=>`<tr><td>${new Date(s.sale_date+'T12:00').toLocaleDateString('pt-BR')}</td><td>${s.customer_name}</td><td>${s.seller}</td><td>${s.payment_method}</td><td>${money(s.sale_value)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhuma venda.</td></tr>'}</tbody></table></div>`;}

window.openVehicle=id=>{editingId=id||null;const v=vehicles.find(x=>x.id===id);$('#vehicleId').value=id||'';$('#vehicleModalTitle').textContent=v?'Editar veículo':'Novo veículo';$('#vmMarca').value=v?.brand||'';$('#vmModelo').value=v?.model||'';$('#vmVersao').value=v?.version||'';$('#vmAno').value=v?.year_model||'';$('#vmKm').value=v?numberBR(v.mileage):'';$('#vmPreco').value=v?money(v.price):'';$('#vmCategoria').value=v?.category||'SUV';$('#vmStatus').value=v?.status||'Disponível';$('#vmDescricao').value=v?.description||'';selectedFiles=[];renderPhotoState(v);openModal('vehicleModal');};
function renderPhotoState(v){const current=v?photos.filter(p=>p.vehicle_id===v.id):[];$('#vehiclePhotoCounter').textContent=`${current.length} foto(s) salva(s) • ${selectedFiles.length} nova(s)`;$('#vehiclePhotoPreviews').innerHTML=current.map(p=>`<div class="photo-preview"><img src="${p.public_url}"></div>`).join('');$('#vehiclePhotoError').textContent='';}
window.handleVehiclePhotos=e=>{selectedFiles=[...e.target.files].slice(0,10);$('#vehiclePhotoCounter').textContent=`${selectedFiles.length} nova(s) foto(s) selecionada(s)`;$('#vehiclePhotoPreviews').innerHTML=selectedFiles.map(f=>`<div class="photo-preview"><img src="${URL.createObjectURL(f)}"></div>`).join('');};
window.saveVehicle=async e=>{e.preventDefault();const payload={brand:normalizeBrand($('#vmMarca').value),model:$('#vmModelo').value.trim(),version:$('#vmVersao').value.trim(),year_model:$('#vmAno').value.trim(),mileage:Number(digits($('#vmKm').value)),price:Number(digits($('#vmPreco').value)),category:$('#vmCategoria').value,transmission:'Automático',description:$('#vmDescricao').value.trim(),status:$('#vmStatus').value};let vehicleId=editingId;if(editingId){const {error}=await supabase.from('vehicles').update(payload).eq('id',editingId);if(error)return toast(error.message,'error');}else{const {data,error}=await supabase.from('vehicles').insert(payload).select().single();if(error)return toast(error.message,'error');vehicleId=data.id;}if(selectedFiles.length){const existing=photos.filter(p=>p.vehicle_id===vehicleId);for(let i=0;i<selectedFiles.length&&existing.length+i<10;i++){const f=selectedFiles[i],ext=f.name.split('.').pop().toLowerCase(),path=`${vehicleId}/${crypto.randomUUID()}.${ext}`;const {error:upErr}=await supabase.storage.from('vehicle-images').upload(path,f,{contentType:f.type});if(upErr){toast(upErr.message,'error');continue;}const {data:{publicUrl}}=supabase.storage.from('vehicle-images').getPublicUrl(path);await supabase.from('vehicle_photos').insert({vehicle_id:vehicleId,storage_path:path,public_url:publicUrl,position:existing.length+i,is_cover:existing.length===0&&i===0});}}await loadAll();closeModal('vehicleModal');renderVehicles();toast(editingId?'Veículo atualizado.':'Veículo cadastrado.');};
window.deleteVehicle=async id=>{if(!confirm('Excluir este veículo?'))return;const related=photos.filter(p=>p.vehicle_id===id);if(related.length)await supabase.storage.from('vehicle-images').remove(related.map(p=>p.storage_path));const {error}=await supabase.from('vehicles').delete().eq('id',id);if(error)return toast(error.message,'error');await loadAll();renderVehicles();toast('Veículo excluído.');};

window.openLead=()=>{fillVehicleSelect($('#lmVeiculo'));$('#leadId').value='';$('#lmNome').value='';$('#lmTelefone').value='';$('#lmEmail').value='';$('#lmStatus').value='Novo';$('#lmVendedor').value='';$('#lmOrigem').value='Site';$('#lmData').value=today();$('#lmObs').value='';openModal('leadModal');};
function fillVehicleSelect(el){el.innerHTML='<option value="">Selecione o veículo</option>'+vehicles.map(v=>`<option value="${v.id}">${normalizeBrand(v.brand)} ${v.model}</option>`).join('');}
window.saveLead=async e=>{e.preventDefault();const payload={name:$('#lmNome').value.trim(),phone:$('#lmTelefone').value.trim(),email:$('#lmEmail').value.trim()||null,status:$('#lmStatus').value,vehicle_id:$('#lmVeiculo').value||null,seller:$('#lmVendedor').value.trim()||null,source:$('#lmOrigem').value.trim()||null,contact_date:$('#lmData').value,notes:$('#lmObs').value.trim()||null};const {error}=await supabase.from('leads').insert(payload);if(error)return toast(error.message,'error');await loadAll();closeModal('leadModal');renderLeads();toast('Lead cadastrado.');};
window.deleteLead=async id=>{if(!confirm('Excluir este lead?'))return;await supabase.from('leads').delete().eq('id',id);await loadAll();renderLeads();};
window.openSale=()=>{fillVehicleSelect($('#smVehicle'));$('#smCustomer').value='';$('#smSeller').value='';$('#smDate').value=today();$('#smValue').value='';$('#smNotes').value='';openModal('saleModal');};
window.saveSale=async e=>{e.preventDefault();const payload={vehicle_id:$('#smVehicle').value,customer_name:$('#smCustomer').value.trim(),seller:$('#smSeller').value.trim(),sale_date:$('#smDate').value,sale_value:Number($('#smValue').value),payment_method:$('#smPayment').value,notes:$('#smNotes').value.trim()||null};const {error}=await supabase.from('sales').insert(payload);if(error)return toast(error.message,'error');await loadAll();closeModal('saleModal');renderSales();toast('Venda registrada.');};
function openModal(id){$('#'+id).classList.add('open');}window.closeModal=id=>$('#'+id).classList.remove('open');

document.addEventListener('input',e=>{if(e.target.id==='vmKm')e.target.value=numberBR(digits(e.target.value));if(e.target.id==='vmPreco')e.target.value=digits(e.target.value)?money(digits(e.target.value)):'';});
boot();
