import { supabase } from './supabase-config.js';
import { money,numberBR,digits,normalizeBrand,toast } from './utils.js';
const $=s=>document.querySelector(s);let vehicles=[],leads=[],sales=[],photos=[];let selectedFiles=[];let editingId=null;let coverChoice=null;const today=()=>new Date().toISOString().slice(0,10);
async function boot(){const {data:{session}}=await supabase.auth.getSession();session?showApp():showLogin();supabase.auth.onAuthStateChange((_e,s)=>s?showApp():showLogin());}
function showLogin(){$('#loginScreen').classList.remove('hidden');$('#app').classList.add('hidden');}
async function showApp(){$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');await loadAll();goPage('dashboard',document.querySelector('[data-page="dashboard"]'));}
window.login=async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)toast('E-mail ou senha inválidos.','error');};window.logout=async()=>supabase.auth.signOut();
async function loadAll(){const [v,l,s,p]=await Promise.all([supabase.from('vehicles').select('*').order('created_at',{ascending:false}),supabase.from('leads').select('*').order('contact_date',{ascending:false}),supabase.from('sales').select('*').order('sale_date',{ascending:false}),supabase.from('vehicle_photos').select('*').order('position')]);if(v.error||l.error||s.error||p.error){console.error(v.error,l.error,s.error,p.error);toast('Erro ao carregar dados.','error');return;}vehicles=v.data||[];leads=l.data||[];sales=s.data||[];photos=p.data||[];}
window.goPage=(page,btn)=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');$('#topTitle').textContent={dashboard:'Dashboard',vehicles:'Veículos',leads:'CRM / Leads',sales:'Vendas'}[page];renderPage(page);};
function renderPage(page){if(page==='dashboard')renderDashboard();if(page==='vehicles')renderVehicles();if(page==='leads')renderLeads();if(page==='sales')renderSales();}
function renderDashboard(){const revenue=sales.reduce((a,s)=>a+Number(s.sale_value),0);$('#pageContent').innerHTML=`<div class="page-head"><div><h1>Visão geral</h1><p>Dados em tempo real do Supabase.</p></div></div><div class="stats"><div class="stat"><span>Veículos vendidos</span><strong>${sales.length}</strong></div><div class="stat"><span>Faturamento</span><strong>${money(revenue)}</strong></div><div class="stat"><span>Ticket médio</span><strong>${money(sales.length?revenue/sales.length:0)}</strong></div><div class="stat"><span>Estoque disponível</span><strong>${vehicles.filter(v=>v.status==='Disponível').length}</strong></div></div>`;}
function renderVehicles(){$('#pageContent').innerHTML=`<div class="page-head"><div><h1>Veículos</h1><p>Cadastre e edite o estoque no Supabase.</p></div><button class="primary" onclick="openVehicle()">+ Novo veículo</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Veículo</th><th>Ano</th><th>KM</th><th>Preço</th><th>Status</th><th>Ações</th></tr></thead><tbody>${vehicles.map(v=>`<tr><td><b>${normalizeBrand(v.brand)} ${v.model}</b><br><small>${v.version}</small></td><td>${v.year_model}</td><td>${numberBR(v.mileage)}</td><td>${money(v.price)}</td><td><span class="badge">${v.status}</span></td><td><button class="mini" onclick="openVehicle('${v.id}')">Editar</button> <button class="mini danger" onclick="deleteVehicle('${v.id}')">Excluir</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhum veículo cadastrado.</td></tr>'}</tbody></table></div>`;}
function renderLeads(){$('#pageContent').innerHTML=`<div class="page-head"><div><h1>CRM / Leads</h1><p>Gerencie oportunidades comerciais.</p></div><button class="primary" onclick="openLead()">+ Novo lead</button></div>`;}
function renderSales(){const total=sales.reduce((a,s)=>a+Number(s.sale_value),0);$('#pageContent').innerHTML=`<div class="page-head"><div><h1>Vendas</h1><p>Resultados registrados no banco.</p></div><button class="primary" onclick="openSale()">+ Registrar venda</button></div><div class="stats"><div class="stat"><span>Vendidos</span><strong>${sales.length}</strong></div><div class="stat"><span>Faturamento</span><strong>${money(total)}</strong></div><div class="stat"><span>Ticket médio</span><strong>${money(sales.length?total/sales.length:0)}</strong></div></div>`;}
function currentPhotos(){return editingId?photos.filter(p=>p.vehicle_id===editingId).sort((a,b)=>a.position-b.position):[];}
window.openVehicle=id=>{editingId=id||null;const v=vehicles.find(x=>x.id===id);$('#vehicleId').value=id||'';$('#vehicleModalTitle').textContent=v?'Editar veículo':'Novo veículo';$('#vmMarca').value=v?.brand||'';$('#vmModelo').value=v?.model||'';$('#vmVersao').value=v?.version||'';$('#vmAno').value=v?.year_model||'';$('#vmKm').value=v?numberBR(v.mileage):'';$('#vmPreco').value=v?money(v.price):'';$('#vmCategoria').value=v?.category||'';$('#vmCambio').value=v?.transmission||'';$('#vmStatus').value=v?.status||'Disponível';$('#vmDescricao').value=v?.description||'';selectedFiles=[];const current=currentPhotos();coverChoice=current.find(p=>p.is_cover)?.id||(current[0]?.id||null);renderPhotoState();openModal('vehicleModal');};
function renderPhotoState(){const current=currentPhotos();const all=[...current.map(p=>({kind:'saved',key:p.id,src:p.public_url})),...selectedFiles.map((f,i)=>({kind:'new',key:`new-${i}`,src:URL.createObjectURL(f)}))];$('#vehiclePhotoCounter').textContent=`${current.length} salva(s) • ${selectedFiles.length} nova(s) • ${all.length}/10`;$('#vehiclePhotoPreviews').innerHTML=all.map(x=>`<div class="photo-preview ${coverChoice===x.key?'cover-selected':''}" onclick="setCover('${x.key}')"><img src="${x.src}">${coverChoice===x.key?'<span class="cover-label">CAPA</span>':''}</div>`).join('');$('#vehiclePhotoError').textContent='';}
window.setCover=key=>{coverChoice=key;renderPhotoState();};
window.handleVehiclePhotos=e=>{const current=currentPhotos();const incoming=[...e.target.files];if(current.length+incoming.length>10){$('#vehiclePhotoError').textContent='O veículo pode ter no máximo 10 fotos.';e.target.value='';return;}selectedFiles=incoming;if(!coverChoice&&selectedFiles.length)coverChoice='new-0';renderPhotoState();e.target.value='';};
window.saveVehicle=async e=>{e.preventDefault();const transmission=$('#vmCambio').value;if(!transmission)return toast('Selecione o câmbio.','error');const payload={brand:normalizeBrand($('#vmMarca').value),model:$('#vmModelo').value.trim(),version:$('#vmVersao').value.trim(),year_model:$('#vmAno').value.trim(),mileage:Number(digits($('#vmKm').value)),price:Number(digits($('#vmPreco').value)),category:$('#vmCategoria').value,transmission,description:$('#vmDescricao').value.trim(),status:$('#vmStatus').value};let vehicleId=editingId;if(editingId){const {error}=await supabase.from('vehicles').update(payload).eq('id',editingId);if(error)return toast(error.message,'error');}else{const {data,error}=await supabase.from('vehicles').insert(payload).select().single();if(error)return toast(error.message,'error');vehicleId=data.id;}const existing=photos.filter(p=>p.vehicle_id===vehicleId).sort((a,b)=>a.position-b.position);let inserted=[];for(let i=0;i<selectedFiles.length&&existing.length+i<10;i++){const f=selectedFiles[i],ext=f.name.split('.').pop().toLowerCase(),path=`${vehicleId}/${crypto.randomUUID()}.${ext}`;const {error:upErr}=await supabase.storage.from('vehicle-images').upload(path,f,{contentType:f.type});if(upErr)return toast(upErr.message,'error');const {data:{publicUrl}}=supabase.storage.from('vehicle-images').getPublicUrl(path);const {data,error}=await supabase.from('vehicle_photos').insert({vehicle_id:vehicleId,storage_path:path,public_url:publicUrl,position:existing.length+i,is_cover:false}).select().single();if(error)return toast(error.message,'error');inserted.push(data);}const all=[...existing,...inserted];let chosenId=null;if(String(coverChoice).startsWith('new-')){const idx=Number(String(coverChoice).replace('new-',''));chosenId=inserted[idx]?.id||null;}else chosenId=coverChoice;if(!chosenId&&all.length)chosenId=all[0].id;if(all.length){await supabase.from('vehicle_photos').update({is_cover:false}).eq('vehicle_id',vehicleId);if(chosenId)await supabase.from('vehicle_photos').update({is_cover:true}).eq('id',chosenId);}await loadAll();closeModal('vehicleModal');renderVehicles();toast(editingId?'Veículo atualizado.':'Veículo cadastrado.');};
window.deleteVehicle=async id=>{if(!confirm('Excluir este veículo?'))return;const related=photos.filter(p=>p.vehicle_id===id);if(related.length)await supabase.storage.from('vehicle-images').remove(related.map(p=>p.storage_path));const {error}=await supabase.from('vehicles').delete().eq('id',id);if(error)return toast(error.message,'error');await loadAll();renderVehicles();toast('Veículo excluído.');};
window.openLead=()=>openModal('leadModal');window.openSale=()=>openModal('saleModal');function openModal(id){$('#'+id).classList.add('open');}window.closeModal=id=>$('#'+id).classList.remove('open');
document.addEventListener('input',e=>{if(e.target.id==='vmKm')e.target.value=numberBR(digits(e.target.value));if(e.target.id==='vmPreco')e.target.value=digits(e.target.value)?money(digits(e.target.value)):'';});boot();