const menuButton = document.querySelector('.menu-toggle');
const navigation = document.querySelector('.main-nav');
if (menuButton && navigation) { menuButton.addEventListener('click',()=>{const isOpen=navigation.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(isOpen));}); navigation.addEventListener('click',()=>{navigation.classList.remove('open');menuButton.setAttribute('aria-expanded','false');}); }

// O índice é estático; artigos editoriais novos são inseridos aqui para que a home,
// busca, filtros e contadores sejam atualizados no mesmo deploy.
const articleGrid=document.querySelector('.article-grid');
if(articleGrid && !articleGrid.querySelector('a[href="artigos/url-uri-endereco-web.html"]')){
  articleGrid.insertAdjacentHTML('afterbegin','<article class="article-card featured" data-category="fundamentos" data-search="url uri endereço web scheme esquema domínio host porta caminho path query string parâmetros fragmento link"><div class="card-visual"><img src="assets/images/capa-internet.webp" alt="Roteador Wi-Fi e switch de rede conectados por cabos" width="1440" height="810"></div><div class="card-content"><div class="card-meta"><span>Fundamentos</span><time datetime="2026-09-15">15 set 2026</time></div><h3><a href="artigos/url-uri-endereco-web.html">URL e URI: entenda cada parte de um endereço da Web</a></h3><p>Aprenda a ler protocolo, domínio, porta, caminho, parâmetros e fragmentos de uma URL.</p><div class="card-footer"><span>13 min de leitura</span><a href="artigos/url-uri-endereco-web.html" aria-label="Ler artigo sobre URL e URI">Ler artigo →</a></div></div></article>');
}
if(articleGrid && !articleGrid.querySelector('a[href="artigos/sql-group-by-having.html"]')){
  articleGrid.insertAdjacentHTML('afterbegin','<article class="article-card featured" data-category="banco" data-search="sql group by having count sum avg min max agregação agrupamento relatório vendas postgres banco dados"><div class="card-visual"><img src="assets/images/capa-sql-filtros.webp" alt="Pessoa analisando dados em um tablet ao lado de um computador" width="1440" height="810"></div><div class="card-content"><div class="card-meta"><span>Banco de Dados</span><time datetime="2026-09-18">18 set 2026</time></div><h3><a href="artigos/sql-group-by-having.html">SQL GROUP BY e HAVING na prática</a></h3><p>Agrupe dados, calcule totais e médias e aprenda quando usar WHERE ou HAVING.</p><div class="card-footer"><span>15 min de leitura</span><a href="artigos/sql-group-by-having.html" aria-label="Ler artigo sobre GROUP BY e HAVING">Ler artigo →</a></div></div></article>');
}
if(articleGrid){const total=articleGrid.querySelectorAll('.article-card').length;document.querySelectorAll('.stats strong').forEach((el)=>{if(/^\d+$/.test(el.textContent.trim()))el.textContent=String(total);});}

const searchInput=document.querySelector('#busca');
const filterButtons=[...document.querySelectorAll('.filter-button')];
const cards=[...document.querySelectorAll('.article-card')];
const emptyState=document.querySelector('#sem-resultados');
const resultCount=document.querySelector('#resultados-contagem');
const clearSearchButton=document.querySelector('[data-clear-search]');
let activeCategory='todos';
const requestedCategory=new URLSearchParams(window.location.search).get('categoria');
if(requestedCategory&&filterButtons.some((button)=>button.dataset.filter===requestedCategory)){activeCategory=requestedCategory;filterButtons.forEach((button)=>{const isActive=button.dataset.filter===requestedCategory;button.classList.toggle('active',isActive);button.setAttribute('aria-pressed',String(isActive));});}
function normalizeText(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function filterArticles(){const term=normalizeText(searchInput?.value||'');let visible=0;cards.forEach((card)=>{const matchesCategory=activeCategory==='todos'||card.dataset.category===activeCategory;const searchable=normalizeText(`${card.dataset.search||''} ${card.textContent}`);const matchesSearch=!term||searchable.includes(term);const shouldShow=matchesCategory&&matchesSearch;card.hidden=!shouldShow;if(shouldShow)visible+=1;});if(emptyState)emptyState.hidden=visible!==0;if(resultCount)resultCount.textContent=`${visible} ${visible===1?'artigo encontrado':'artigos encontrados'}`;if(clearSearchButton)clearSearchButton.hidden=!term;}
function updateCategoryUrl(){const url=new URL(window.location.href);if(activeCategory==='todos')url.searchParams.delete('categoria');else url.searchParams.set('categoria',activeCategory);window.history.replaceState({},'',`${url.pathname}${url.search}${url.hash}`);}
filterButtons.forEach((button)=>{button.addEventListener('click',()=>{activeCategory=button.dataset.filter||'todos';filterButtons.forEach((item)=>{const isActive=item===button;item.classList.toggle('active',isActive);item.setAttribute('aria-pressed',String(isActive));});updateCategoryUrl();filterArticles();});});
searchInput?.addEventListener('input',filterArticles);searchInput?.addEventListener('keydown',(event)=>{if(event.key==='Escape'&&searchInput.value){searchInput.value='';filterArticles();}});clearSearchButton?.addEventListener('click',()=>{if(!searchInput)return;searchInput.value='';searchInput.focus();filterArticles();});if(cards.length)filterArticles();
const article=document.querySelector('.article-body');const progressBar=document.querySelector('.reading-progress span');
function updateReadingProgress(){if(!article||!progressBar)return;const articleTop=article.getBoundingClientRect().top+window.scrollY;const scrollable=Math.max(article.offsetHeight-window.innerHeight,1);const progress=Math.min(100,Math.max(0,((window.scrollY-articleTop+120)/scrollable)*100));progressBar.style.width=`${progress}%`;}
if(article&&progressBar){updateReadingProgress();window.addEventListener('scroll',updateReadingProgress,{passive:true});window.addEventListener('resize',updateReadingProgress);}
const pageUrl=encodeURIComponent(window.location.href);const pageTitle=encodeURIComponent(document.title.replace(' — Código em Sala',''));
document.querySelectorAll('[data-share="whatsapp"]').forEach((link)=>{link.href=`https://wa.me/?text=${pageTitle}%20${pageUrl}`;});document.querySelectorAll('[data-share="facebook"]').forEach((link)=>{link.href=`https://www.facebook.com/sharer/sharer.php?u=${pageUrl}`;});document.querySelectorAll('[data-share="native"]').forEach((button)=>{if(!navigator.share){button.hidden=true;return;}button.addEventListener('click',()=>navigator.share({title:document.title,url:window.location.href}).catch(()=>{}));});
if(!document.querySelector('#aviso-cookies')){document.body.insertAdjacentHTML('beforeend',`<aside id="aviso-cookies" class="cookie-banner" aria-label="Preferências de cookies" aria-live="polite"><p><strong>Cookies e privacidade</strong>Você pode aceitar a personalização ou continuar apenas com recursos essenciais. A publicidade, quando disponível, respeita essa escolha. <a href="${document.body.dataset.article==='true'?'../':''}privacidade.html">Saiba mais</a>.</p><div class="cookie-actions"><button class="cookie-button" type="button" data-cookie-choice="essenciais">Somente essenciais</button><button class="cookie-button primary" type="button" data-cookie-choice="aceitos">Aceitar</button></div></aside>`);}
const cookieBanner=document.querySelector('#aviso-cookies');const cookieChoice=localStorage.getItem('codigo-em-sala-cookies');if(cookieBanner&&!cookieChoice)cookieBanner.classList.add('open');document.querySelectorAll('[data-cookie-choice]').forEach((button)=>{button.addEventListener('click',()=>{const accepted=button.dataset.cookieChoice==='aceitos';localStorage.setItem('codigo-em-sala-cookies',button.dataset.cookieChoice);window.gtag?.('consent','update',{ad_storage:accepted?'granted':'denied',ad_user_data:accepted?'granted':'denied',ad_personalization:accepted?'granted':'denied',analytics_storage:accepted?'granted':'denied'});cookieBanner?.classList.remove('open');});});document.querySelectorAll('[data-cookie-settings]').forEach((button)=>{button.addEventListener('click',()=>cookieBanner?.classList.add('open'));});