const $=s=>document.querySelector(s),money=v=>(+v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}),today=()=>new Date().toISOString().slice(0,10);
let VEHICLES=JSON.parse(localStorage.getItem('altura-vehicles-v2')||'[]');
let LEADS=JSON.parse(localStorage.getItem('altura-crm-leads')||'null')||[
{id:1,nome:'Carlos Eduardo',telefone:'(89) 99999-1111',email:'',status:'Novo',vehicleId:VEHICLES[0]?.id||'',vendedor:'Marina',origem:'WhatsApp',data:today(),obs:'Solicitou detalhes.'},
{id:2,nome:'Paula Mendes',telefone:'(89) 99999-2222',email:'',status:'Negociação',vehicleId:VEHICLES[1]?.id||'',vendedor:'Ricardo',origem:'Instagram',data:today(),obs:'Possui usado na troca.'},
{id:3,nome:'João Victor',telefone:'(89) 99999-3333',email:'',status:'Proposta enviada',vehicleId:VEHICLES[2]?.id||'',vendedor:'Marina',origem:'Site',data:today(),obs:'Aguardando retorno.'}
];
let SALES=JSON.parse(localStorage.getItem('altura-crm-sales')||'[]'),currentPage='dashboard';
function persist(){localStorage.setItem('altura-vehicles-v2',JSON.stringify(VEHICLES));localStorage.setItem('altura-crm-leads',JSON.stringify(LEADS));localStorage.setItem('altura-crm-sales',JSON.stringify(SALES))}
function login(e){e.preventDefault();sessionStorage.setItem('altura-admin','1');$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');render()}
function logout(){sessionStorage.removeItem('altura-admin');location.reload()}
if(sessionStorage.getItem('altura-admin')){$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden')}
function goPage(page,btn){currentPage=page;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');$('#topTitle').textContent={dashboard:'Dashboard',vehicles:'Veículos',leads:'CRM / Leads',sales:'Vendas'}[page];render()}
function filterSales(){const from=$('#filterFrom')?.value||'',to=$('#filterTo')?.value||'',seller=$('#filterSeller')?.value||'';return SALES.filter(s=>(!from||s.date>=from)&&(!to||s.date<=to)&&(!seller||s.seller===seller))}
function dashboard(){
 const sold=filterSales(),revenue=sold.reduce((a,s)=>a+s.value,0),ticket=sold.length?revenue/sold.length:0;
 const statuses=['Novo','Em atendimento','Proposta enviada','Negociação','Vendido'];
 const sellers=[...new Set(SALES.map(s=>s.seller))];
 const months=[...Array(6)].map((_,i)=>{const d=new Date();d.setMonth(d.getMonth()-(5-i));return {key:d.toISOString().slice(0,7),label:d.toLocaleDateString('pt-BR',{month:'short'})}});
 const values=months.map(m=>SALES.filter(s=>s.date.startsWith(m.key)).reduce((a,s)=>a+s.value,0)),max=Math.max(...values,1);
 return `<div class="page-head"><div><h1>Visão geral</h1><p>Acompanhe estoque, funil comercial e resultados.</p></div><div class="actions"><button class="secondary" onclick="openLead()">+ Novo lead</button><button class="primary" onclick="openSale()">+ Registrar venda</button></div></div>
 <div class="filters"><input id="filterFrom" type="date" onchange="render()"><input id="filterTo" type="date" onchange="render()"><select id="filterSeller" onchange="render()"><option value="">Todos os vendedores</option>${sellers.map(x=>`<option>${x}</option>`).join('')}</select><button class="secondary" onclick="clearDashboardFilters()">Limpar período</button></div>
 <div class="stats"><div class="stat"><span>Veículos vendidos</span><strong>${sold.length}</strong><small>No período selecionado</small></div><div class="stat"><span>Faturamento</span><strong>${money(revenue)}</strong><small>Total vendido</small></div><div class="stat"><span>Ticket médio</span><strong>${money(ticket)}</strong><small>Por venda</small></div><div class="stat"><span>Estoque disponível</span><strong>${VEHICLES.filter(v=>v.status==='Disponível').length}</strong><small>${VEHICLES.length} cadastrados</small></div></div>
 <div class="dashboard-grid"><section class="panel"><h3>Faturamento dos últimos 6 meses</h3><div class="bars">${months.map((m,i)=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(4,values[i]/max*190)}px" title="${money(values[i])}"></div><small>${m.label}</small></div>`).join('')}</div></section><section class="panel"><h3>Funil comercial</h3><div class="pipeline">${statuses.map(s=>`<div class="pipe"><strong>${LEADS.filter(l=>l.status===s).length}</strong><span>${s}</span></div>`).join('')}</div></section></div>`;
}
function vehiclesPage(){return `<div class="page-head"><div><h1>Veículos</h1><p>Cadastre, edite e acompanhe o status do estoque.</p></div><button class="primary" onclick="openVehicle()">+ Novo veículo</button></div>
 <div class="filters"><select id="vehicleStatusFilter" onchange="renderVehiclesTable()"><option value="">Todos os status</option><option>Disponível</option><option>Reservado</option><option>Vendido</option></select><input id="vehicleSearch" placeholder="Buscar marca ou modelo" oninput="renderVehiclesTable()"></div><div class="table-wrap"><table class="table"><thead><tr><th>Veículo</th><th>Ano</th><th>KM</th><th>Preço</th><th>Status</th><th>Ações</th></tr></thead><tbody id="vehiclesRows"></tbody></table></div>`}
function leadsPage(){const sellers=[...new Set(LEADS.map(l=>l.vendedor))];return `<div class="page-head"><div><h1>CRM / Leads</h1><p>Controle contatos, negociações e oportunidades.</p></div><button class="primary" onclick="openLead()">+ Novo lead</button></div>
 <div class="filters"><select id="leadStatusFilter" onchange="renderLeadsTable()"><option value="">Todos os status</option>${['Novo','Em atendimento','Proposta enviada','Negociação','Vendido','Perdido'].map(x=>`<option>${x}</option>`).join('')}</select><select id="leadSellerFilter" onchange="renderLeadsTable()"><option value="">Todos os vendedores</option>${sellers.map(x=>`<option>${x}</option>`).join('')}</select><input id="leadSearch" placeholder="Buscar cliente ou telefone" oninput="renderLeadsTable()"></div><div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>Interesse</th><th>Vendedor</th><th>Origem</th><th>Data</th><th>Status</th><th>Ações</th></tr></thead><tbody id="leadsRows"></tbody></table></div>`}
function salesPage(){const sellers=[...new Set(SALES.map(s=>s.seller))];return `<div class="page-head"><div><h1>Vendas</h1><p>Consulte quantos veículos foram vendidos e o faturamento.</p></div><button class="primary" onclick="openSale()">+ Registrar venda</button></div>
 <div class="filters"><input id="salesFrom" type="date" onchange="renderSalesTable()"><input id="salesTo" type="date" onchange="renderSalesTable()"><select id="salesSeller" onchange="renderSalesTable()"><option value="">Todos os vendedores</option>${sellers.map(x=>`<option>${x}</option>`).join('')}</select><button class="secondary" onclick="clearSalesFilters()">Limpar</button></div><div id="salesSummary"></div><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Veículo</th><th>Cliente</th><th>Vendedor</th><th>Pagamento</th><th>Valor</th><th>Ações</th></tr></thead><tbody id="salesRows"></tbody></table></div>`}
function render(){const c=$('#pageContent');c.innerHTML=currentPage==='dashboard'?dashboard():currentPage==='vehicles'?vehiclesPage():currentPage==='leads'?leadsPage():salesPage();if(currentPage==='vehicles')renderVehiclesTable();if(currentPage==='leads')renderLeadsTable();if(currentPage==='sales')renderSalesTable()}
function renderVehiclesTable(){const q=($('#vehicleSearch')?.value||'').toLowerCase(),st=$('#vehicleStatusFilter')?.value||'';const list=VEHICLES.filter(v=>(!st||v.status===st)&&(`${v.marca} ${v.modelo} ${v.versao}`.toLowerCase().includes(q)));$('#vehiclesRows').innerHTML=list.map(v=>`<tr><td><b>${v.marca} ${v.modelo}</b><br><small>${v.versao}</small></td><td>${v.ano}</td><td>${(+v.km).toLocaleString('pt-BR')}</td><td>${money(v.preco)}</td><td><span class="badge ${v.status==='Vendido'?'Vendido-veiculo':v.status}">${v.status}</span></td><td><button class="mini" onclick="openVehicle(${v.id})">Editar</button> <button class="mini danger" onclick="deleteVehicle(${v.id})">Excluir</button></td></tr>`).join('')||`<tr><td colspan="6" class="empty">Nenhum veículo encontrado.</td></tr>`}
function renderLeadsTable(){const q=($('#leadSearch')?.value||'').toLowerCase(),st=$('#leadStatusFilter')?.value||'',seller=$('#leadSellerFilter')?.value||'';const list=LEADS.filter(l=>(!st||l.status===st)&&(!seller||l.vendedor===seller)&&(`${l.nome} ${l.telefone}`.toLowerCase().includes(q)));$('#leadsRows').innerHTML=list.map(l=>{const v=VEHICLES.find(v=>String(v.id)===String(l.vehicleId));return `<tr><td><b>${l.nome}</b><br><small>${l.telefone}</small></td><td>${v?`${v.marca} ${v.modelo}`:'Não informado'}</td><td>${l.vendedor}</td><td>${l.origem||'-'}</td><td>${new Date(l.data+'T12:00').toLocaleDateString('pt-BR')}</td><td><span class="badge ${l.status.replaceAll(' ','-')}">${l.status}</span></td><td><button class="mini" onclick="openLead(${l.id})">Editar</button> <button class="mini danger" onclick="deleteLead(${l.id})">Excluir</button></td></tr>`}).join('')||`<tr><td colspan="7" class="empty">Nenhum lead encontrado.</td></tr>`}
function getSalesFiltered(){const from=$('#salesFrom')?.value||'',to=$('#salesTo')?.value||'',seller=$('#salesSeller')?.value||'';return SALES.filter(s=>(!from||s.date>=from)&&(!to||s.date<=to)&&(!seller||s.seller===seller))}
function renderSalesTable(){const list=getSalesFiltered(),total=list.reduce((a,s)=>a+s.value,0);$('#salesSummary').innerHTML=`<div class="stats"><div class="stat"><span>Veículos vendidos</span><strong>${list.length}</strong></div><div class="stat"><span>Faturamento</span><strong>${money(total)}</strong></div><div class="stat"><span>Ticket médio</span><strong>${money(list.length?total/list.length:0)}</strong></div><div class="stat"><span>Vendedores</span><strong>${new Set(list.map(s=>s.seller)).size}</strong></div></div>`;$('#salesRows').innerHTML=list.map(s=>{const v=VEHICLES.find(v=>String(v.id)===String(s.vehicleId));return `<tr><td>${new Date(s.date+'T12:00').toLocaleDateString('pt-BR')}</td><td>${v?`${v.marca} ${v.modelo}`:'Veículo removido'}</td><td>${s.customer}</td><td>${s.seller}</td><td>${s.payment}</td><td><b>${money(s.value)}</b></td><td><button class="mini danger" onclick="deleteSale(${s.id})">Excluir</button></td></tr>`}).join('')||`<tr><td colspan="7" class="empty">Nenhuma venda no período.</td></tr>`}
function clearDashboardFilters(){['filterFrom','filterTo','filterSeller'].forEach(id=>{if($('#'+id))$('#'+id).value=''});render()}
function clearSalesFilters(){['salesFrom','salesTo','salesSeller'].forEach(id=>$('#'+id).value='');renderSalesTable()}
function openVehicle(id=''){const v=VEHICLES.find(x=>String(x.id)===String(id));$('#vehicleId').value=v?.id||'';$('#vehicleModalTitle').textContent=v?'Editar veículo':'Novo veículo';$('#vmMarca').value=v?.marca||'';$('#vmModelo').value=v?.modelo||'';$('#vmVersao').value=v?.versao||'';$('#vmAno').value=v?.ano||'';$('#vmKm').value=v?.km||'';$('#vmPreco').value=v?.preco||'';$('#vmCategoria').value=v?.categoria||'SUV';$('#vmStatus').value=v?.status||'Disponível';$('#vmFoto').value=v?.fotos?.[0]||'';$('#vmDescricao').value=v?.descricao||'';openModal('vehicleModal')}
function saveVehicle(e){e.preventDefault();const id=$('#vehicleId').value,old=VEHICLES.find(v=>String(v.id)===String(id));const obj={...old,id:id?+id:Date.now(),marca:$('#vmMarca').value,modelo:$('#vmModelo').value,versao:$('#vmVersao').value,ano:$('#vmAno').value,km:+$('#vmKm').value,preco:+$('#vmPreco').value,categoria:$('#vmCategoria').value,status:$('#vmStatus').value,fotos:[$('#vmFoto').value,...(old?.fotos||[]).slice(1)],descricao:$('#vmDescricao').value,cambio:old?.cambio||'Automático',selos:old?.selos||[],opcionais:old?.opcionais||[]};VEHICLES=id?VEHICLES.map(v=>String(v.id)===String(id)?obj:v):[obj,...VEHICLES];persist();closeModal('vehicleModal');render()}
function deleteVehicle(id){if(confirm('Excluir este veículo?')){VEHICLES=VEHICLES.filter(v=>v.id!==id);persist();render()}}
function fillVehicleSelect(sel,value=''){sel.innerHTML='<option value="">Selecione o veículo</option>'+VEHICLES.map(v=>`<option value="${v.id}" ${String(v.id)===String(value)?'selected':''}>${v.marca} ${v.modelo} - ${v.ano}</option>`).join('')}
function openLead(id=''){const l=LEADS.find(x=>String(x.id)===String(id));$('#leadId').value=l?.id||'';$('#leadModalTitle').textContent=l?'Editar lead':'Novo lead';$('#lmNome').value=l?.nome||'';$('#lmTelefone').value=l?.telefone||'';$('#lmEmail').value=l?.email||'';$('#lmStatus').value=l?.status||'Novo';fillVehicleSelect($('#lmVeiculo'),l?.vehicleId);$('#lmVendedor').value=l?.vendedor||'';$('#lmOrigem').value=l?.origem||'Site';$('#lmData').value=l?.data||today();$('#lmObs').value=l?.obs||'';openModal('leadModal')}
function saveLead(e){e.preventDefault();const id=$('#leadId').value,obj={id:id?+id:Date.now(),nome:$('#lmNome').value,telefone:$('#lmTelefone').value,email:$('#lmEmail').value,status:$('#lmStatus').value,vehicleId:$('#lmVeiculo').value,vendedor:$('#lmVendedor').value,origem:$('#lmOrigem').value,data:$('#lmData').value,obs:$('#lmObs').value};LEADS=id?LEADS.map(l=>String(l.id)===String(id)?obj:l):[obj,...LEADS];persist();closeModal('leadModal');render()}
function deleteLead(id){if(confirm('Excluir este lead?')){LEADS=LEADS.filter(l=>l.id!==id);persist();render()}}
function openSale(){fillVehicleSelect($('#smVehicle'));$('#saleId').value='';$('#smCustomer').value='';$('#smSeller').value='';$('#smDate').value=today();$('#smValue').value='';$('#smNotes').value='';openModal('saleModal')}
function saveSale(e){e.preventDefault();const vehicleId=$('#smVehicle').value,obj={id:Date.now(),vehicleId,customer:$('#smCustomer').value,seller:$('#smSeller').value,date:$('#smDate').value,value:+$('#smValue').value,payment:$('#smPayment').value,notes:$('#smNotes').value};SALES=[obj,...SALES];VEHICLES=VEHICLES.map(v=>String(v.id)===String(vehicleId)?{...v,status:'Vendido'}:v);const lead=LEADS.find(l=>String(l.vehicleId)===String(vehicleId)&&l.nome.toLowerCase()===obj.customer.toLowerCase());if(lead)lead.status='Vendido';persist();closeModal('saleModal');render()}
function deleteSale(id){if(confirm('Excluir este registro de venda?')){SALES=SALES.filter(s=>s.id!==id);persist();render()}}
function openModal(id){$('#'+id).classList.add('open')}function closeModal(id){$('#'+id).classList.remove('open')}
render();