const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=v=>(+v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const FALLBACK='https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1400&q=85';
const DEFAULT_VEHICLES=[
{id:1,marca:'BMW',modelo:'320i',versao:'Sport GP',ano:'2023/2024',km:18400,preco:239900,status:'Disponível',categoria:'Sedan',cambio:'Automático',combustivel:'Flex',cor:'Preto',motor:'2.0 Turbo',potencia:'184 cv',tracao:'Traseira',fotos:['https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1400&q=85'],descricao:'Sedã premium com excelente desempenho, conforto e tecnologia.',selos:['Premium','Revisado'],opcionais:['Bancos em couro','Teto solar','Central multimídia'],slug:'bmw-320i-sport-gp'},
{id:2,marca:'Audi',modelo:'A3 Sedan',versao:'Performance Black',ano:'2022/2023',km:27600,preco:214900,status:'Disponível',categoria:'Sedan',cambio:'Automático',combustivel:'Flex',cor:'Cinza',motor:'2.0 Turbo',potencia:'190 cv',tracao:'Dianteira',fotos:['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=85'],descricao:'Design sofisticado e ótimo conjunto tecnológico.',selos:['Premium'],opcionais:['Painel digital','Faróis LED','Chave presencial'],slug:'audi-a3-sedan'},
{id:3,marca:'Jeep',modelo:'Compass',versao:'Limited T270',ano:'2023/2024',km:12900,preco:179900,status:'Disponível',categoria:'SUV',cambio:'Automático',combustivel:'Flex',cor:'Branco',motor:'1.3 Turbo',potencia:'185 cv',tracao:'Dianteira',fotos:['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=85'],descricao:'SUV completo, confortável e com baixa quilometragem.',selos:['Baixa KM','Revisado'],opcionais:['Câmera 360°','Piloto automático','Ar digital'],slug:'jeep-compass-limited'},
{id:4,marca:'Toyota',modelo:'Corolla',versao:'XEi 2.0',ano:'2023/2024',km:22100,preco:148900,status:'Reservado',categoria:'Sedan',cambio:'Automático',combustivel:'Flex',cor:'Prata',motor:'2.0',potencia:'177 cv',tracao:'Dianteira',fotos:['https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=1400&q=85'],descricao:'Confiabilidade, conforto e excelente valor de revenda.',selos:['Reservado'],opcionais:['Controle de estabilidade','Multimídia','Bancos em couro'],slug:'toyota-corolla-xei'},
{id:5,marca:'Volkswagen',modelo:'T-Cross',versao:'Highline 250 TSI',ano:'2022/2023',km:31800,preco:129900,status:'Disponível',categoria:'SUV',cambio:'Automático',combustivel:'Flex',cor:'Azul',motor:'1.4 Turbo',potencia:'150 cv',tracao:'Dianteira',fotos:['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1400&q=85'],descricao:'SUV urbano com bom desempenho e ótimo espaço interno.',selos:['Revisado'],opcionais:['Painel digital','Sensor de estacionamento','Partida por botão'],slug:'volkswagen-t-cross'},
{id:6,marca:'Fiat',modelo:'Toro',versao:'Volcano Turbo',ano:'2023/2024',km:19600,preco:159900,status:'Disponível',categoria:'Picape',cambio:'Automático',combustivel:'Diesel',cor:'Vermelho',motor:'2.0 Turbo Diesel',potencia:'170 cv',tracao:'4x4',fotos:['https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1400&q=85'],descricao:'Picape versátil, forte e confortável para trabalho e lazer.',selos:['4x4','Revisado'],opcionais:['Tração 4x4','Capota marítima','Câmera de ré'],slug:'fiat-toro-volcano'}
];
let stored;try{stored=JSON.parse(localStorage.getItem('altura-vehicles-v2')||'null')}catch(e){stored=null}
let VEHICLES=Array.isArray(stored)&&stored.length?stored:DEFAULT_VEHICLES;
VEHICLES=VEHICLES.map((v,i)=>({...DEFAULT_VEHICLES[i%DEFAULT_VEHICLES.length],...v,fotos:Array.isArray(v.fotos)&&v.fotos[0]?v.fotos:DEFAULT_VEHICLES[i%DEFAULT_VEHICLES.length].fotos}));
localStorage.setItem('altura-vehicles-v2',JSON.stringify(VEHICLES));
let favorites=JSON.parse(localStorage.getItem('altura-favs')||'[]'),compare=[],currentGallery=[],galleryIndex=0,zoomed=false;
function safeImg(v){return v?.fotos?.[0]||FALLBACK}
function init(){
 const brands=[...new Set(VEHICLES.map(v=>v.marca))],cats=[...new Set(VEHICLES.map(v=>v.categoria))];
 $('#fBrand').innerHTML='<option value="">Todas</option>'+brands.map(x=>`<option>${x}</option>`).join('');
 $('#fCategory').innerHTML='<option value="">Todas</option>'+cats.map(x=>`<option>${x}</option>`).join('');
 $('#brandRow').innerHTML=brands.map(x=>`<button class="brand-chip" onclick="filterBrand('${x}')">${x}</button>`).join('');
 render();
 const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});$$('.reveal').forEach(el=>obs.observe(el));
}
function filtered(){return VEHICLES.filter(v=>(!$('#fBrand').value||v.marca===$('#fBrand').value)&&(!$('#fCategory').value||v.categoria===$('#fCategory').value)&&(!$('#fCambio').value||v.cambio===$('#fCambio').value)&&(!$('#fPrice').value||v.preco<=+$('#fPrice').value)&&(!$('#fKm').value||v.km<=+$('#fKm').value))}
function render(list=filtered()){
 $('#resultCount').textContent=`${list.length} veículos encontrados`;
 $('#vehicleGrid').innerHTML=list.map(v=>`<article class="card ${v.status==='Vendido'?'sold':''}"><img src="${safeImg(v)}" alt="${v.marca} ${v.modelo}" loading="lazy" onerror="this.onerror=null;this.src='${FALLBACK}'">${v.status==='Vendido'?'<div class="sold-ribbon">VENDIDO</div>':''}<span class="status">${v.status||'Disponível'}</span><button class="fav ${favorites.includes(v.id)?'active':''}" onclick="toggleFav(${v.id},event)">♡</button><div class="card-overlay"><div class="brand-label">${v.marca}</div><h3>${v.modelo}</h3><div class="version">${v.versao}</div><div class="card-bottom"><div><div class="price">${money(v.preco)}</div><div class="meta">${v.ano} • ${(+v.km).toLocaleString('pt-BR')} km • ${v.cambio||'Automático'}</div></div><div class="card-actions"><button class="details" onclick="openVehicle(${v.id})">Detalhes</button>${v.status==='Vendido'?'':`<button class="compare" onclick="toggleCompare(${v.id},event)">⇄</button>`}</div></div></div></article>`).join('')||'<p>Nenhum veículo encontrado.</p>';
}
['fBrand','fCategory','fCambio','fPrice','fKm'].forEach(id=>document.addEventListener('input',e=>e.target.id===id&&render()));
function clearFilters(){['fBrand','fCategory','fCambio','fPrice','fKm'].forEach(id=>$('#'+id).value='');$('#aiSearch').value='';$('#clearSearchBtn').classList.remove('show');render();setTimeout(()=>$('#estoque').scrollIntoView({behavior:'smooth'}),80)}
function filterBrand(b){$('#fBrand').value=b;render();$('#estoque').scrollIntoView({behavior:'smooth'})}
function normalizeText(t){return String(t||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function smartSearch(){const raw=$('#aiSearch').value.trim(),q=normalizeText(raw);$('#clearSearchBtn').classList.toggle('show',!!raw);if(!q){render();return}const terms=q.split(/\s+/).filter(x=>x.length>1&&!['quero','um','uma','carro','veiculo','ate','mil','com'].includes(x));const list=VEHICLES.filter(v=>terms.every(t=>normalizeText([v.marca,v.modelo,v.versao,v.categoria,v.cambio,v.combustivel].join(' ')).includes(t)));render(list);setTimeout(()=>$('#estoque').scrollIntoView({behavior:'smooth'}),80)}
$('#aiSearch').addEventListener('input',e=>$('#clearSearchBtn').classList.toggle('show',!!e.target.value.trim()));$('#aiSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();smartSearch()}});
function toggleFav(id,e){e?.stopPropagation();favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('altura-favs',JSON.stringify(favorites));render()}
function showFavorites(){render(VEHICLES.filter(v=>favorites.includes(v.id)));$('#estoque').scrollIntoView({behavior:'smooth'})}
function openVehicle(id){const v=VEHICLES.find(x=>String(x.id)===String(id));if(!v)return;currentGallery=v.fotos;$('#vehicleContent').innerHTML=`<div class="breadcrumb">Início / Estoque / ${v.marca} / ${v.modelo}</div><div class="vehicle-page"><section class="gallery"><div class="main-photo"><img id="mainPhoto" src="${safeImg(v)}" onerror="this.src='${FALLBACK}'" onclick="openLightbox(0)"><span class="photo-count">${v.fotos.length} foto(s)</span></div></section><aside class="vehicle-info"><div class="brand-label">${v.marca}</div><h2>${v.modelo}</h2><div class="version">${v.versao}</div><div class="price">${money(v.preco)}</div><p>${v.descricao||''}</p><div class="specs"><div class="spec"><small>Ano</small><strong>${v.ano}</strong></div><div class="spec"><small>KM</small><strong>${(+v.km).toLocaleString('pt-BR')} km</strong></div><div class="spec"><small>Câmbio</small><strong>${v.cambio}</strong></div><div class="spec"><small>Combustível</small><strong>${v.combustivel||'-'}</strong></div></div><div class="vehicle-actions"><a class="wa" target="_blank" href="https://wa.me/5589981311034?text=${encodeURIComponent('Olá! Tenho interesse no '+v.marca+' '+v.modelo)}">Falar no WhatsApp</a><button class="secondary" onclick="shareVehicle('${v.slug||''}')">Compartilhar</button></div></aside></div>`;$('#vehicleModal').classList.add('open');document.body.classList.add('lock')}
function closeModal(){$('#vehicleModal').classList.remove('open');document.body.classList.remove('lock')}
function openLightbox(i){galleryIndex=i;$('#lightboxImg').src=currentGallery[i]||FALLBACK;$('#lightbox').classList.add('open')}
function stepLightbox(d){galleryIndex=(galleryIndex+d+currentGallery.length)%currentGallery.length;$('#lightboxImg').src=currentGallery[galleryIndex]||FALLBACK;$('#lbCount').textContent=`${galleryIndex+1} / ${currentGallery.length}`}
function zoomLightbox(){zoomed=!zoomed;$('#lightboxImg').style.transform=zoomed?'scale(1.5)':'scale(1)'}function closeLightbox(){$('#lightbox').classList.remove('open')}
async function shareVehicle(slug){const url=location.href.split('#')[0]+'#veiculo/'+slug;if(navigator.share)await navigator.share({title:'Altura Motors',url});else{await navigator.clipboard.writeText(url);alert('Link copiado!')}}
function toggleCompare(id,e){e.stopPropagation();compare=compare.includes(id)?compare.filter(x=>x!==id):[...compare,id].slice(-2);$('#compareBar').classList.toggle('show',compare.length>0);$('#compareText').textContent=compare.length+' selecionado(s)'}function openCompare(){if(compare.length<2)return alert('Selecione dois veículos.');alert('Comparação demonstrativa disponível.')}
window.addEventListener('storage',e=>{if(e.key==='altura-vehicles-v2'){try{VEHICLES=JSON.parse(e.newValue)||VEHICLES;render()}catch(_){}}});
init();